---
name: "Setup Environment"
description: "Install dependencies in the most efficient way for Node/Bun project."

runs:
  using: "composite"
  steps:
    - name: Prepare System
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
        version: 1.0

    - name: Setup Environment
      uses: 0xTheProDev/setup-js@c0c49ac6d2b6d33876ce0176aea8e4a6bbcb8a71
      with:
        cache: pnpm
        registry-url: "https://registry.npmjs.org"
        version-file: .nvmrc

branding:
  icon: "package"
  color: "green"
