---
name: "Setup Environment"
description: "Install dependencies in the most efficient way for Node/Bun project."

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Install Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: .bun-version

    - name: Load Dependency Cache
      uses: actions/cache@v4
      with:
        path: "~/.bun/install/cache"
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
        restore-keys: |
          ${{ runner.os }}-bun-

    - name: Install Dependencies
      shell: bash
      run: |
        bun install --frozen-lockfile

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: "package"
  color: "green"
