---
name: Build
on:
  push:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"
  pull_request:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "18.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap --ignore-scripts

      - name: Build Artifacts
        run: yarn build
