# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Build
on:
  push:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "*.yml"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"
  pull_request:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "*.yml"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Prepare Environment
        uses: ./.github/shared/setup

      - name: Build Artifacts
        run: pnpm build
