---
name: Build
on:
  push:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "*.yaml"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"
  pull_request:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "*.yaml"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
      - "!packages/**/__mocks__/**"
      - "!packages/**/__tests__/**"

jobs:
  build:
    name: Build Artifacts
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.10"]
    steps:
      - name: 'Setup Workspace Env (Temporary)'
        run: |-
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v2
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Artifacts
        run: pnpm build
