---
name: Deployment
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ["20.10"]
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - uses: actions/setup-node@v2
        with:
          cache: "pnpm"
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Lerna
        run: pnpm add -g lerna@4

      - name: Install Dependencies
        run: lerna bootstrap --ignore-scripts

      - name: Build Artifacts
        run: pnpm build

      - name: Publish to NPM
        run: lerna publish from-git --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
