# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: Deployment
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - name: Prepare Environment
        uses: ./.github/shared/setup

      - name: Build Artifacts
        run: pnpm build

      - name: Publish to NPM
        run: lerna publish from-git --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
