---
name: Deployment
on:
  push:
    tags:
      - "*"

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node for NPM
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
          scope: "@operational-transformation"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: npm install -g lerna

      - name: Install Dependencies
        run: lerna bootstrap --ignore-scripts

      - name: Build Artifacts
        run: lerna exec yarn build

      - name: Publish to NPM
        run: lerna publish from-git --yes --no-verify-access
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
