---
name: "Code Quality"

on:
  push:
    branches:
      - main
    paths:
      - "packages/**/*.ts"
  pull_request:
    branches:
      - main
    paths:
      - "packages/**/*.ts"

jobs:
  analyze:
    name: Analyze Code Quality
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          config-file: ./codeql.config.yml
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
