# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
---
name: "Code Quality"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "packages/**/*.ts"

jobs:
  analyze:
    name: Analyze Code Quality
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language:
          - javascript-typescript

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          config-file: ./codeql.config.yml
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
