---
name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "!**.md"
      - "__tests__/**"
      - "packages/**"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
  pull_request:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "!**.md"
      - "__tests__/**"
      - "packages/**"
      - "!examples/**/*.js"
      - "!examples/**/*.json"

jobs:
  unit:
    name: Unit Test Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Run Tests
        run: "yarn test:ci"

      - uses: actions/upload-artifact@v2
        with:
          name: unit-tests-coverage
          path: coverage-root/coverage-final.json
          if-no-files-found: error

  monaco:
    name: Monaco Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Run Tests
        run: "yarn test:monaco"

      - uses: actions/upload-artifact@v2
        with:
          name: monaco-integration-coverage
          path: coverage-monaco/coverage-final.json
          if-no-files-found: error

  coverage:
    name: Generate Coverage Report
    needs: [unit, monaco]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn

      - uses: actions/download-artifact@v2

      - name: LS
        run: ls -R

      - name: Generate Coverage Report
        run: yarn coverage

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
          fail_ci_if_error: true
