---
name: Tests
on:
  push:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "__tests__/**"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"
  pull_request:
    branches:
      - main
    paths:
      - "*.js"
      - "*.json"
      - "__tests__/**"
      - "packages/**"
      - "!**.md"
      - "!examples/**/*.js"
      - "!examples/**/*.json"

jobs:
  unit:
    name: Unit Test Modules
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Run Tests
        run: "yarn test:ci"

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-unit-tests
          path: coverage-root/coverage-final.json
          if-no-files-found: error

  ace:
    name: Ace Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Run Tests
        run: "yarn test:ace"

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-ace-integration
          path: coverage-ace/coverage-final.json
          if-no-files-found: error

  firebase:
    name: Firebase Integration
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
            $HOME/.cache
            $HOME/firebase
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Add Realtime Database Rules
        uses: jsdaniell/create-json@1.1.2
        with:
          name: "database.rules.json"
          json: ${{ secrets.FIREBASE_DATABASE_JSON }}
          dir: "__tests__/firebase/.firebase/"

      - name: Run Tests
        run: "yarn test:firebase"

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-firebase-integration
          path: coverage-firebase/coverage-final.json
          if-no-files-found: error

  monaco:
    name: Monaco Integration
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Lerna
        run: yarn global add lerna@4

      - name: Install Dependencies
        run: lerna bootstrap

      - name: Run Tests
        run: "yarn test:monaco"

      - uses: actions/upload-artifact@v2
        with:
          name: coverage-monaco-integration
          path: coverage-monaco/coverage-final.json
          if-no-files-found: error

  coverage:
    name: Generate Coverage Report
    needs: [unit, ace, firebase, monaco]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            $HOME/.npm
            $HOME/.yarn-cache
          key: ${{ runner.OS }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn

      - uses: actions/download-artifact@v2

      - name: Generate Coverage Report
        run: yarn coverage

      - name: Upload Coverage Report to Codecov
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
          fail_ci_if_error: true
